logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.bzu.smartvax: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/smartvax_copy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: reemreem2024
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    contexts: dev, faker
  mail:
    host: smtp.gmail.com
    port: 587
    username: smartvax99@gmail.com
    password: gfivcxcgkvpyaadi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

server:
  port: 8080
  forward-headers-strategy: native

jhipster:
  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:9060,https://localhost:9060,http://localhost:3000'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: OTRiYjIyZWM2OTNkMzg2ZTYxMjc1YjczY2Y1MDVhY2U4M2Y3MWExZjFmODI5NGQzYmYxZjE0YmM5NTNmMjEyZjg0NWM2NjExZTBiOGYwNjJkNzU1NTgxOWE0NmQ3ZGFlZjUzMjIwYmM0NjEwZjk5MzU4MGRiM2QyOTg2ZjY1NTc=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
