package com.bzu.smartvax.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HealthRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHealthRecordAllPropertiesEquals(HealthRecord expected, HealthRecord actual) {
        assertHealthRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertHealthRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHealthRecordAllUpdatablePropertiesEquals(HealthRecord expected, HealthRecord actual) {
        assertHealthRecordUpdatableFieldsEquals(expected, actual);
        assertHealthRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHealthRecordAutoGeneratedPropertiesEquals(HealthRecord expected, HealthRecord actual) {
        assertThat(actual)
            .as("Verify HealthRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHealthRecordUpdatableFieldsEquals(HealthRecord expected, HealthRecord actual) {
        assertThat(actual)
            .as("Verify HealthRecord relevant properties")
            .satisfies(a -> assertThat(a.getSensitivity()).as("check sensitivity").isEqualTo(expected.getSensitivity()))
            .satisfies(a -> assertThat(a.getDiabetes()).as("check diabetes").isEqualTo(expected.getDiabetes()))
            .satisfies(a -> assertThat(a.getHighBloodPressure()).as("check highBloodPressure").isEqualTo(expected.getHighBloodPressure()))
            .satisfies(a -> assertThat(a.getGeneticDiseases()).as("check geneticDiseases").isEqualTo(expected.getGeneticDiseases()))
            .satisfies(a -> assertThat(a.getBloodType()).as("check bloodType").isEqualTo(expected.getBloodType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHealthRecordUpdatableRelationshipsEquals(HealthRecord expected, HealthRecord actual) {
        // empty method
    }
}
